
version: "3.3"

services: 
  api:
    build: .
    image: node-nginx-docker
    container_name: node-nginx-docker
    restart: unless-stopped
    volumes:
      - .:/usr/src/app
      - "usr/src/app/node_modules"
    ports:
      - 4000:4000
    depends_on:
      - mysql
    environment:
      - DB_HOST=mysql
      - DB_PASS=123
      - DB_NAME=test
      - DB_USER=ye
    networks:
      - app-network
  nginx:
    build: 
      context: ./config/nginx
      args:
        - CERTBOT_EMAIL=berkassebrahim@gmail.com
        - DOMAIN_LIST=hecticsolution.xyz
    image: nginx-certbot
    container_name: web-proxy
    restart: unless-stopped
    volumes:
      - ./config/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/config/conf.d/prod:/etc/nginx/conf.d
      - letsencrypt:/etc/letsencrypt
    ports:
      - 80:80
      - 443:443
    depends_on:
      - api
    networks:
      - app-network
  mysql:
    build: ./config/database
    command: --default-authentication-plugin=mysql_native_password
    restart: always 
    ports:
      - 3318:3306
    networks:
      - app-network
      
networks:
  app-network:
    driver: bridge